// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateJob(arg1) {
  return window['go']['main']['App']['CreateJob'](arg1);
}

export function CreatePythonVirtualEnv(arg1, arg2) {
  return window['go']['main']['App']['CreatePythonVirtualEnv'](arg1, arg2);
}

export function CreateSamplePlugin() {
  return window['go']['main']['App']['CreateSamplePlugin']();
}

export function DeleteImportedFile(arg1) {
  return window['go']['main']['App']['DeleteImportedFile'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function DeleteVirtualEnvironment(arg1) {
  return window['go']['main']['App']['DeleteVirtualEnvironment'](arg1);
}

export function DetectPythonEnvironments() {
  return window['go']['main']['App']['DetectPythonEnvironments']();
}

export function DetectPythonPath() {
  return window['go']['main']['App']['DetectPythonPath']();
}

export function DetectREnvironments() {
  return window['go']['main']['App']['DetectREnvironments']();
}

export function DetectRPath() {
  return window['go']['main']['App']['DetectRPath']();
}

export function DownloadPortableEnvironment(arg1, arg2) {
  return window['go']['main']['App']['DownloadPortableEnvironment'](arg1, arg2);
}

export function ExecutePlugin(arg1) {
  return window['go']['main']['App']['ExecutePlugin'](arg1);
}

export function ExecutePythonScript(arg1, arg2) {
  return window['go']['main']['App']['ExecutePythonScript'](arg1, arg2);
}

export function ExecuteRScript(arg1, arg2) {
  return window['go']['main']['App']['ExecuteRScript'](arg1, arg2);
}

export function GetActivePythonEnvironment() {
  return window['go']['main']['App']['GetActivePythonEnvironment']();
}

export function GetActiveREnvironment() {
  return window['go']['main']['App']['GetActiveREnvironment']();
}

export function GetAllJobs() {
  return window['go']['main']['App']['GetAllJobs']();
}

export function GetBundledRequirementsPath(arg1) {
  return window['go']['main']['App']['GetBundledRequirementsPath'](arg1);
}

export function GetExampleFilePath(arg1, arg2) {
  return window['go']['main']['App']['GetExampleFilePath'](arg1, arg2);
}

export function GetImportedFiles() {
  return window['go']['main']['App']['GetImportedFiles']();
}

export function GetJob(arg1) {
  return window['go']['main']['App']['GetJob'](arg1);
}

export function GetJobQueueStatus() {
  return window['go']['main']['App']['GetJobQueueStatus']();
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function GetPlugin(arg1) {
  return window['go']['main']['App']['GetPlugin'](arg1);
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetPluginsDirectory() {
  return window['go']['main']['App']['GetPluginsDirectory']();
}

export function GetPortableEnvironmentPath(arg1) {
  return window['go']['main']['App']['GetPortableEnvironmentPath'](arg1);
}

export function GetPortableEnvironmentURL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPortableEnvironmentURL'](arg1, arg2, arg3, arg4);
}

export function GetPythonVersion() {
  return window['go']['main']['App']['GetPythonVersion']();
}

export function GetRVersion() {
  return window['go']['main']['App']['GetRVersion']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVirtualEnvironments() {
  return window['go']['main']['App']['GetVirtualEnvironments']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleQuit() {
  return window['go']['main']['App']['HandleQuit']();
}

export function HasInProgressJobs() {
  return window['go']['main']['App']['HasInProgressJobs']();
}

export function ImportDataFile(arg1) {
  return window['go']['main']['App']['ImportDataFile'](arg1);
}

export function InstallPythonPackages(arg1, arg2) {
  return window['go']['main']['App']['InstallPythonPackages'](arg1, arg2);
}

export function InstallPythonRequirements(arg1, arg2) {
  return window['go']['main']['App']['InstallPythonRequirements'](arg1, arg2);
}

export function InstallRPackages(arg1, arg2) {
  return window['go']['main']['App']['InstallRPackages'](arg1, arg2);
}

export function ListPythonPackages(arg1) {
  return window['go']['main']['App']['ListPythonPackages'](arg1);
}

export function ListRPackages(arg1) {
  return window['go']['main']['App']['ListRPackages'](arg1);
}

export function LoadRPackagesFromFile(arg1) {
  return window['go']['main']['App']['LoadRPackagesFromFile'](arg1);
}

export function LogToFile(arg1) {
  return window['go']['main']['App']['LogToFile'](arg1);
}

export function OpenDataFileDialog() {
  return window['go']['main']['App']['OpenDataFileDialog']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenDirectoryInExplorer(arg1) {
  return window['go']['main']['App']['OpenDirectoryInExplorer'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenLogDirectory() {
  return window['go']['main']['App']['OpenLogDirectory']();
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function ParseDataFile(arg1, arg2) {
  return window['go']['main']['App']['ParseDataFile'](arg1, arg2);
}

export function PauseJobQueue() {
  return window['go']['main']['App']['PauseJobQueue']();
}

export function ReExecuteJob(arg1) {
  return window['go']['main']['App']['ReExecuteJob'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFilePreview(arg1, arg2) {
  return window['go']['main']['App']['ReadFilePreview'](arg1, arg2);
}

export function ReadJobOutputFile(arg1, arg2) {
  return window['go']['main']['App']['ReadJobOutputFile'](arg1, arg2);
}

export function ReloadPlugins() {
  return window['go']['main']['App']['ReloadPlugins']();
}

export function RerunJob(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RerunJob'](arg1, arg2, arg3, arg4);
}

export function ResumeJobQueue() {
  return window['go']['main']['App']['ResumeJobQueue']();
}

export function RunNormalization(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunNormalization'](arg1, arg2, arg3, arg4);
}

export function RunPCAAnalysis(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunPCAAnalysis'](arg1, arg2, arg3, arg4, arg5);
}

export function RunPHATEAnalysis(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunPHATEAnalysis'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SetActivePythonEnvironment(arg1) {
  return window['go']['main']['App']['SetActivePythonEnvironment'](arg1);
}

export function SetActiveREnvironment(arg1) {
  return window['go']['main']['App']['SetActiveREnvironment'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StopJobQueueImmediate() {
  return window['go']['main']['App']['StopJobQueueImmediate']();
}

export function WriteJobOutputFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteJobOutputFile'](arg1, arg2, arg3);
}
