// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function CreateJob(arg1:models.JobRequest):Promise<string>;

export function CreatePythonVirtualEnv(arg1:string,arg2:string):Promise<void>;

export function CreateSamplePlugin():Promise<void>;

export function DeleteImportedFile(arg1:number):Promise<void>;

export function DeleteJob(arg1:string):Promise<void>;

export function DeleteVirtualEnvironment(arg1:number):Promise<void>;

export function DetectPythonEnvironments():Promise<Array<services.PythonEnvironment>>;

export function DetectPythonPath():Promise<string>;

export function DetectREnvironments():Promise<Array<services.REnvironment>>;

export function DetectRPath():Promise<string>;

export function DownloadPortableEnvironment(arg1:string,arg2:string):Promise<void>;

export function ExecutePlugin(arg1:models.PluginExecutionRequest):Promise<string>;

export function ExecutePluginV2(arg1:models.PluginExecutionRequestV2):Promise<string>;

export function ExecutePythonScript(arg1:string,arg2:Array<string>):Promise<string>;

export function ExecuteRScript(arg1:string,arg2:Array<string>):Promise<string>;

export function GetActivePythonEnvironment():Promise<services.PythonEnvironment>;

export function GetActiveREnvironment():Promise<services.REnvironment>;

export function GetAllJobs():Promise<Array<models.Job>>;

export function GetBundledRequirementsPath(arg1:string):Promise<string>;

export function GetExampleFilePath(arg1:string,arg2:string):Promise<string>;

export function GetImportedFiles():Promise<Array<services.ImportedFile>>;

export function GetJob(arg1:string):Promise<models.Job>;

export function GetJobQueueStatus():Promise<Record<string, any>>;

export function GetLogFilePath():Promise<string>;

export function GetPlugin(arg1:string):Promise<models.Plugin>;

export function GetPluginV2(arg1:string):Promise<models.PluginV2>;

export function GetPlugins():Promise<Array<models.Plugin>>;

export function GetPluginsDirectory():Promise<string>;

export function GetPluginsV2():Promise<Array<models.PluginV2>>;

export function GetPortableEnvironmentPath(arg1:string):Promise<string>;

export function GetPortableEnvironmentURL(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetPythonVersion():Promise<string>;

export function GetRVersion():Promise<string>;

export function GetSettings():Promise<models.Config>;

export function GetVirtualEnvironments():Promise<Array<services.VirtualEnvironment>>;

export function Greet(arg1:string):Promise<string>;

export function HandleQuit():Promise<void>;

export function HasInProgressJobs():Promise<boolean>;

export function ImportDataFile(arg1:string):Promise<number>;

export function InstallPythonPackages(arg1:string,arg2:Array<string>):Promise<void>;

export function InstallPythonRequirements(arg1:string,arg2:string):Promise<void>;

export function InstallRPackages(arg1:string,arg2:Array<string>):Promise<void>;

export function ListPythonPackages(arg1:string):Promise<Array<string>>;

export function ListRPackages(arg1:string):Promise<Array<string>>;

export function LoadRPackagesFromFile(arg1:string):Promise<Array<string>>;

export function LogToFile(arg1:string):Promise<void>;

export function OpenDataFileDialog():Promise<string>;

export function OpenDirectory(arg1:string):Promise<string>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenDirectoryInExplorer(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<string>;

export function OpenLogDirectory():Promise<void>;

export function OpenLogFile():Promise<void>;

export function ParseDataFile(arg1:string,arg2:number):Promise<services.DataFilePreview>;

export function PauseJobQueue():Promise<void>;

export function ReExecuteJob(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<Array<number>>;

export function ReadFilePreview(arg1:string,arg2:number):Promise<Array<string>>;

export function ReadJobOutputFile(arg1:string,arg2:string):Promise<string>;

export function ReloadPlugins():Promise<void>;

export function ReloadPluginsV2():Promise<void>;

export function RerunJob(arg1:string,arg2:boolean,arg3:string,arg4:string):Promise<string>;

export function ResumeJobQueue():Promise<void>;

export function RunNormalization(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<string>;

export function RunPCAAnalysis(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:boolean):Promise<string>;

export function RunPHATEAnalysis(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:boolean):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SetActivePythonEnvironment(arg1:string):Promise<void>;

export function SetActiveREnvironment(arg1:string):Promise<void>;

export function SetSetting(arg1:string,arg2:any):Promise<void>;

export function StopJobQueueImmediate():Promise<void>;

export function WriteJobOutputFile(arg1:string,arg2:string,arg3:string):Promise<void>;
