// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindPluginToEnvironment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BindPluginToEnvironment'](arg1, arg2, arg3, arg4);
}

export function CheckDockerVersion() {
  return window['go']['main']['App']['CheckDockerVersion']();
}

export function CheckPluginUpdate(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckPluginUpdate'](arg1, arg2, arg3);
}

export function ConfirmPluginInstallation(arg1, arg2) {
  return window['go']['main']['App']['ConfirmPluginInstallation'](arg1, arg2);
}

export function ConfirmPluginInstallationWithRegistry(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfirmPluginInstallationWithRegistry'](arg1, arg2, arg3);
}

export function ConvertPluginToYAML(arg1) {
  return window['go']['main']['App']['ConvertPluginToYAML'](arg1);
}

export function CreatePythonVirtualEnv(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePythonVirtualEnv'](arg1, arg2, arg3);
}

export function CreateRenvEnvironment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateRenvEnvironment'](arg1, arg2, arg3, arg4);
}

export function CreateSamplePlugin() {
  return window['go']['main']['App']['CreateSamplePlugin']();
}

export function DecodePluginRepoURL(arg1) {
  return window['go']['main']['App']['DecodePluginRepoURL'](arg1);
}

export function DeleteCustomEnvVar(arg1) {
  return window['go']['main']['App']['DeleteCustomEnvVar'](arg1);
}

export function DeleteCustomEnvVarByKey(arg1, arg2) {
  return window['go']['main']['App']['DeleteCustomEnvVarByKey'](arg1, arg2);
}

export function DeleteGitAuthConfig(arg1) {
  return window['go']['main']['App']['DeleteGitAuthConfig'](arg1);
}

export function DeleteImportedFile(arg1) {
  return window['go']['main']['App']['DeleteImportedFile'](arg1);
}

export function DeleteJob(arg1) {
  return window['go']['main']['App']['DeleteJob'](arg1);
}

export function DeletePlugin(arg1) {
  return window['go']['main']['App']['DeletePlugin'](arg1);
}

export function DeletePluginEnvironmentBinding(arg1, arg2) {
  return window['go']['main']['App']['DeletePluginEnvironmentBinding'](arg1, arg2);
}

export function DeleteRenvEnvironment(arg1) {
  return window['go']['main']['App']['DeleteRenvEnvironment'](arg1);
}

export function DeleteVirtualEnvironment(arg1) {
  return window['go']['main']['App']['DeleteVirtualEnvironment'](arg1);
}

export function DetectPythonEnvironments() {
  return window['go']['main']['App']['DetectPythonEnvironments']();
}

export function DetectPythonPath() {
  return window['go']['main']['App']['DetectPythonPath']();
}

export function DetectREnvironments() {
  return window['go']['main']['App']['DetectREnvironments']();
}

export function DetectRPath() {
  return window['go']['main']['App']['DetectRPath']();
}

export function DownloadPortableEnvironment(arg1, arg2) {
  return window['go']['main']['App']['DownloadPortableEnvironment'](arg1, arg2);
}

export function EnableAllPlugins() {
  return window['go']['main']['App']['EnableAllPlugins']();
}

export function ExecutePlugin(arg1) {
  return window['go']['main']['App']['ExecutePlugin'](arg1);
}

export function ExecutePluginV2(arg1) {
  return window['go']['main']['App']['ExecutePluginV2'](arg1);
}

export function ForceUpdateAllRemotePlugins() {
  return window['go']['main']['App']['ForceUpdateAllRemotePlugins']();
}

export function GetActivePythonEnvironment() {
  return window['go']['main']['App']['GetActivePythonEnvironment']();
}

export function GetActiveREnvironment() {
  return window['go']['main']['App']['GetActiveREnvironment']();
}

export function GetAllGitAuthConfigs() {
  return window['go']['main']['App']['GetAllGitAuthConfigs']();
}

export function GetAllJobs() {
  return window['go']['main']['App']['GetAllJobs']();
}

export function GetAllPluginEnvironmentBindings() {
  return window['go']['main']['App']['GetAllPluginEnvironmentBindings']();
}

export function GetBundledRequirementsPath(arg1) {
  return window['go']['main']['App']['GetBundledRequirementsPath'](arg1);
}

export function GetCustomEnvVars(arg1) {
  return window['go']['main']['App']['GetCustomEnvVars'](arg1);
}

export function GetDefaultVenvPath(arg1) {
  return window['go']['main']['App']['GetDefaultVenvPath'](arg1);
}

export function GetExampleFilePath(arg1, arg2) {
  return window['go']['main']['App']['GetExampleFilePath'](arg1, arg2);
}

export function GetGitAuthConfig(arg1) {
  return window['go']['main']['App']['GetGitAuthConfig'](arg1);
}

export function GetGlobalCustomEnvVars() {
  return window['go']['main']['App']['GetGlobalCustomEnvVars']();
}

export function GetImportedFiles() {
  return window['go']['main']['App']['GetImportedFiles']();
}

export function GetJob(arg1) {
  return window['go']['main']['App']['GetJob'](arg1);
}

export function GetJobExecutionLog(arg1) {
  return window['go']['main']['App']['GetJobExecutionLog'](arg1);
}

export function GetJobQueueStatus() {
  return window['go']['main']['App']['GetJobQueueStatus']();
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function GetPlugin(arg1) {
  return window['go']['main']['App']['GetPlugin'](arg1);
}

export function GetPluginEnvironmentBinding(arg1, arg2) {
  return window['go']['main']['App']['GetPluginEnvironmentBinding'](arg1, arg2);
}

export function GetPluginEnvironmentCount(arg1) {
  return window['go']['main']['App']['GetPluginEnvironmentCount'](arg1);
}

export function GetPluginExampleFilePath(arg1, arg2) {
  return window['go']['main']['App']['GetPluginExampleFilePath'](arg1, arg2);
}

export function GetPluginJobCount(arg1) {
  return window['go']['main']['App']['GetPluginJobCount'](arg1);
}

export function GetPluginRequirements(arg1) {
  return window['go']['main']['App']['GetPluginRequirements'](arg1);
}

export function GetPluginTemplates() {
  return window['go']['main']['App']['GetPluginTemplates']();
}

export function GetPluginV2(arg1) {
  return window['go']['main']['App']['GetPluginV2'](arg1);
}

export function GetPluginVersion(arg1) {
  return window['go']['main']['App']['GetPluginVersion'](arg1);
}

export function GetPlugins() {
  return window['go']['main']['App']['GetPlugins']();
}

export function GetPluginsDirectory() {
  return window['go']['main']['App']['GetPluginsDirectory']();
}

export function GetPluginsV2() {
  return window['go']['main']['App']['GetPluginsV2']();
}

export function GetPortableEnvironmentPath(arg1) {
  return window['go']['main']['App']['GetPortableEnvironmentPath'](arg1);
}

export function GetPortableEnvironmentURL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPortableEnvironmentURL'](arg1, arg2, arg3, arg4);
}

export function GetPythonVersion() {
  return window['go']['main']['App']['GetPythonVersion']();
}

export function GetRVersion() {
  return window['go']['main']['App']['GetRVersion']();
}

export function GetRegistryPlugin(arg1) {
  return window['go']['main']['App']['GetRegistryPlugin'](arg1);
}

export function GetRenvEnvironments() {
  return window['go']['main']['App']['GetRenvEnvironments']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVirtualEnvironments() {
  return window['go']['main']['App']['GetVirtualEnvironments']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleProtocolURL(arg1) {
  return window['go']['main']['App']['HandleProtocolURL'](arg1);
}

export function HandleQuit() {
  return window['go']['main']['App']['HandleQuit']();
}

export function HasInProgressJobs() {
  return window['go']['main']['App']['HasInProgressJobs']();
}

export function ImportDataFile(arg1) {
  return window['go']['main']['App']['ImportDataFile'](arg1);
}

export function InstallPluginFromRegistry(arg1, arg2) {
  return window['go']['main']['App']['InstallPluginFromRegistry'](arg1, arg2);
}

export function InstallPluginFromRepo(arg1, arg2) {
  return window['go']['main']['App']['InstallPluginFromRepo'](arg1, arg2);
}

export function InstallPluginRequirements(arg1) {
  return window['go']['main']['App']['InstallPluginRequirements'](arg1);
}

export function InstallPythonPackages(arg1, arg2) {
  return window['go']['main']['App']['InstallPythonPackages'](arg1, arg2);
}

export function InstallPythonRequirements(arg1, arg2) {
  return window['go']['main']['App']['InstallPythonRequirements'](arg1, arg2);
}

export function InstallRPackages(arg1, arg2) {
  return window['go']['main']['App']['InstallRPackages'](arg1, arg2);
}

export function IsPluginInstalled(arg1) {
  return window['go']['main']['App']['IsPluginInstalled'](arg1);
}

export function ListJobOutputFiles(arg1) {
  return window['go']['main']['App']['ListJobOutputFiles'](arg1);
}

export function ListPythonPackages(arg1) {
  return window['go']['main']['App']['ListPythonPackages'](arg1);
}

export function ListRPackages(arg1) {
  return window['go']['main']['App']['ListRPackages'](arg1);
}

export function ListRegistryCategories() {
  return window['go']['main']['App']['ListRegistryCategories']();
}

export function ListRegistryPlugins(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ListRegistryPlugins'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadRPackagesFromFile(arg1) {
  return window['go']['main']['App']['LoadRPackagesFromFile'](arg1);
}

export function LogToFile(arg1) {
  return window['go']['main']['App']['LogToFile'](arg1);
}

export function OpenDataFileDialog() {
  return window['go']['main']['App']['OpenDataFileDialog']();
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenDirectoryInExplorer(arg1) {
  return window['go']['main']['App']['OpenDirectoryInExplorer'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenLogDirectory() {
  return window['go']['main']['App']['OpenLogDirectory']();
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function ParseDataFile(arg1, arg2) {
  return window['go']['main']['App']['ParseDataFile'](arg1, arg2);
}

export function ParsePluginYAML(arg1) {
  return window['go']['main']['App']['ParsePluginYAML'](arg1);
}

export function PauseJobQueue() {
  return window['go']['main']['App']['PauseJobQueue']();
}

export function PinPluginVersion(arg1, arg2) {
  return window['go']['main']['App']['PinPluginVersion'](arg1, arg2);
}

export function ProcessPendingJobs() {
  return window['go']['main']['App']['ProcessPendingJobs']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFilePreview(arg1, arg2) {
  return window['go']['main']['App']['ReadFilePreview'](arg1, arg2);
}

export function ReadJobOutputFile(arg1, arg2) {
  return window['go']['main']['App']['ReadJobOutputFile'](arg1, arg2);
}

export function ReinstallPlugin(arg1) {
  return window['go']['main']['App']['ReinstallPlugin'](arg1);
}

export function ReloadPlugins() {
  return window['go']['main']['App']['ReloadPlugins']();
}

export function ReloadPluginsV2() {
  return window['go']['main']['App']['ReloadPluginsV2']();
}

export function RerunJob(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RerunJob'](arg1, arg2, arg3, arg4);
}

export function ResumeJobQueue() {
  return window['go']['main']['App']['ResumeJobQueue']();
}

export function SaveCustomEnvVar(arg1) {
  return window['go']['main']['App']['SaveCustomEnvVar'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveGitAuthConfig(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveGitAuthConfig'](arg1, arg2, arg3);
}

export function SavePluginYAML(arg1, arg2) {
  return window['go']['main']['App']['SavePluginYAML'](arg1, arg2);
}

export function SaveTempFile(arg1, arg2) {
  return window['go']['main']['App']['SaveTempFile'](arg1, arg2);
}

export function SetActivePythonEnvironment(arg1) {
  return window['go']['main']['App']['SetActivePythonEnvironment'](arg1);
}

export function SetActiveREnvironment(arg1) {
  return window['go']['main']['App']['SetActiveREnvironment'](arg1);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPluginEnabled'](arg1, arg2);
}

export function SetPluginUpdatePolicy(arg1, arg2) {
  return window['go']['main']['App']['SetPluginUpdatePolicy'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function StopJobQueueImmediate() {
  return window['go']['main']['App']['StopJobQueueImmediate']();
}

export function UninstallPluginFromRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UninstallPluginFromRepo'](arg1, arg2, arg3, arg4);
}

export function UnpinPluginVersion(arg1) {
  return window['go']['main']['App']['UnpinPluginVersion'](arg1);
}

export function UpdateAllRemotePlugins() {
  return window['go']['main']['App']['UpdateAllRemotePlugins']();
}

export function UpdatePluginFromRepo(arg1) {
  return window['go']['main']['App']['UpdatePluginFromRepo'](arg1);
}

export function UpdatePluginFromRepoForce(arg1, arg2) {
  return window['go']['main']['App']['UpdatePluginFromRepoForce'](arg1, arg2);
}

export function UpdatePluginToCommit(arg1, arg2) {
  return window['go']['main']['App']['UpdatePluginToCommit'](arg1, arg2);
}

export function UpdatePluginToCommitForce(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdatePluginToCommitForce'](arg1, arg2, arg3);
}

export function ValidatePluginYAML(arg1) {
  return window['go']['main']['App']['ValidatePluginYAML'](arg1);
}

export function ValidateSSHKey(arg1, arg2) {
  return window['go']['main']['App']['ValidateSSHKey'](arg1, arg2);
}

export function WriteJobOutputFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteJobOutputFile'](arg1, arg2, arg3);
}
