package models

// PluginDependencyGraph is a plugin's resolved dependency tree and system requirements, generated by CI and committed as dependencies.json. SystemRequirements is keyed by GOOS ("linux", "darwin") since apt/brew package names differ per platform.
type PluginDependencyGraph struct {
	GeneratedAt        string                               `json:"generatedAt"`
	RVersion           string                               `json:"rVersion,omitempty"`
	Packages           []PluginDependencyPackage            `json:"packages,omitempty"`
	SystemRequirements map[string][]PluginSystemRequirement `json:"systemRequirements,omitempty"`
}

// PluginDependencyPackage is one resolved package in the dependency graph.
type PluginDependencyPackage struct {
	Name       string `json:"name"`
	Version    string `json:"version,omitempty"`
	Repository string `json:"repository,omitempty"`
}

// PluginSystemRequirement is one OS-level package needed to load a dependency, with the apt/brew package names known to satisfy it.
type PluginSystemRequirement struct {
	Name     string   `json:"name"`
	Packages []string `json:"packages,omitempty"`
}
